application: flannl-masonjar
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /_ah/channel/connected/
  script: _go_app

- url: /_ah/channel/disconnected/
  script: _go_app

- url: /.*
  script: _go_app
  login: required

inbound_services:
    - channel_presence
